name: GitHub Actions
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]  #the workflow is triggered when changes are push to the 'master' branch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: peaceiris/actions-gh-pages@v3 #that will deploy the content of the 'public_dir'
      with:
        github_token: ${{ secrets.GH_PAT }} #Personal Access Token - Github Config
        publish_dir: ./public
